import type { NextPage } from 'next';
import Head from 'next/head';
import WorldBannerVideo from '../src/components/WorldBannerVideo';
import WorldHeadline from '../src/components/WorldHeadline';
import WorldPhaseOne from '../src/components/WorldPhaseOne';

const ImaginaryWorld: NextPage = () => {
  return (
    <div className="page-container">
      <Head>
        <title>Imaginary Ones - Imaginary World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WorldBannerVideo />
      <WorldHeadline />
      <WorldPhaseOne />
    </div>
  );
};

export default ImaginaryWorld;
