import type { NextPage } from 'next';
import Head from 'next/head';
import BannerVideo from '../src/components/BannerVideo';
import Characters from '../src/components/Characters';
import ImaginaryValues from '../src/components/ImaginaryValues';
import Why from '../src/components/Why';
import ImaginaryTeam from '../src/components/ImaginaryTeam';
import FAQ from '../src/components/FAQ';
import Community from '../src/components/Community';
import Good from '../src/components/Good';

const Home: NextPage = () => {
  return (
    <div className="page-container">
      <Head>
        <title>Imaginary Ones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BannerVideo />
      <Good />
      <Why />
      <Characters />
      <ImaginaryValues />
      <ImaginaryTeam />
      <FAQ />
      <Community />
    </div>
  );
};

export default Home;
